# Generated by Django 4.2.7 on 2025-09-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student'),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='program',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.institute'),
        ),
        migrations.AddField(
            model_name='branch',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='academics.program'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='academics.program'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('branch', 'semester', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('student', 'program', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'semester_number')},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('institute', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('program', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('program', 'year_number')},
        ),
    ]
